[global]
  sendAnonymousUsage = false
  checkNewVersion = false

[log]
  level = "INFO"
  format = "common"
  filePath = "/var/log/traefik.log"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = true
    swarmMode = false
    network = "web"
  [providers.file]
    filename = "/etc/traefik/traefik_dynamic.toml"
    watch = true

[api]
  dashboard = true
  debug = false
  insecure = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[certificatesResolvers]
  [certificatesResolvers.letsencrypt]
    [certificatesResolvers.letsencrypt.acme]
      email = "pierre.gourgouillon@gmail.com"
      caServer = "https://acme-v02.api.letsencrypt.org/directory"
      storage = "acme.json"
      keyType = "EC384"
        [certificatesResolvers.letsencrypt.acme.httpChallenge]
          entryPoint = "http"
