[tls]
  [tls.options]
    [tls.options.default]
      minVersion = "VersionTLS12"
      sniStrict = true
      cipherSuites = [
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_AES_128_GCM_SHA256",
        "TLS_AES_256_GCM_SHA384",
        "TLS_CHACHA20_POLY1305_SHA256"
      ]
      curvePreferences = ["CurveP521","CurveP384"]

[http]
  [http.middlewares.compression.compress]
    excludedContentTypes = ["text/event-stream"]

  [http.middlewares.https-redirect.redirectScheme]
    scheme = "https"
    permanent = true

  [http.middlewares.security.headers]
    accessControlMaxAge = 100
    browserXssFilter = true
    contentTypeNosniff = true
    forceSTSHeader = true
    frameDeny = false
    stsIncludeSubdomains = true
    stsPreload = true
    stsSeconds = 315360000
    accessControlAllowMethods = ["GET", "OPTIONS", "PUT", "POST", "UPDATE", "DELETE", "PATCH"]
    accessControlAllowOriginList = ["*"]
    accessControlAllowHeaders = ["content-type", "authorization", "cache-control", "x-requested-with", "upload-source", "x-session-id", "x-lazy-pagination", "x-disable-pagination"]

[http.middlewares]
  [http.middlewares.auth-traefik.basicAuth]
  users = [
  "admin:$apr1$LQQo4jgB$aHaDDy1HANN6wEmYdbzRy1"
]
